### ISSUE TITLE
02_04 blockquote

### ISSUE THREAD

**Issue by richwertz** [planetoftheweb/bootstrap4#5]
My experience with using `<blockquote class="blockquote">`, and `<blockquote class="blockquote blockquote-reverse">` is different. Text within the blockquote tags is not styled the same as in the tutorial- text has no styling at all. `blockquote-reverse` does not cause the text to align right.

![image](https://user-images.githubusercontent.com/13661560/38165382-5d324cfc-34e0-11e8-95aa-7b72d550acfe.png)

**Comment by karlkras** [comment]
`blockquote-reverse` was removed... this course is out of date. Needs to use `text-right` instead.
